# Generated by Django 5.1.5 on 2025-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_concern_subgroup_subgroupverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroupentry",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("supervisor_verified", "Supervisor Verified"),
                    ("quality_verified", "Quality Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
