# Generated by Django 5.1.5 on 2025-02-03 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="product_media/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "mp4", "mov", "xlsx", "xls"]
                            )
                        ],
                    ),
                ),
                (
                    "pdf_version",
                    models.FileField(
                        blank=True, null=True, upload_to="product_media/pdf_versions/"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, default=15, help_text="Duration in seconds"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="SopDisplay.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="stations", to="SopDisplay.product"
                    ),
                ),
                (
                    "selected_media",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stations",
                        to="SopDisplay.productmedia",
                    ),
                ),
            ],
        ),
    ]
